// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __RcppMP_RcppExports_h__
#define __RcppMP_RcppExports_h__

#include "RcppMP_types.hpp"
#include <Rcpp.h>

namespace RcppMP {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("RcppMP", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("RcppMP", "RcppMP_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in RcppMP");
            }
        }
    }

    inline Rcpp::List rcppmpVersions() {
        typedef SEXP(*Ptr_rcppmpVersions)();
        static Ptr_rcppmpVersions p_rcppmpVersions = NULL;
        if (p_rcppmpVersions == NULL) {
            validateSignature("Rcpp::List(*rcppmpVersions)()");
            p_rcppmpVersions = (Ptr_rcppmpVersions)R_GetCCallable("RcppMP", "RcppMP_rcppmpVersions");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_rcppmpVersions();
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<Rcpp::List >(__result);
    }

}

#endif // __RcppMP_RcppExports_h__
