// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __RcppMP_RcppExports_h__
#define __RcppMP_RcppExports_h__

#include <Rcpp.h>

namespace RcppMP {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("RcppMP", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("RcppMP", "RcppMP_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in RcppMP");
            }
        }
    }

    inline int twoPlusTwo() {
        typedef SEXP(*Ptr_twoPlusTwo)();
        static Ptr_twoPlusTwo p_twoPlusTwo = NULL;
        if (p_twoPlusTwo == NULL) {
            validateSignature("int(*twoPlusTwo)()");
            p_twoPlusTwo = (Ptr_twoPlusTwo)R_GetCCallable("RcppMP", "RcppMP_twoPlusTwo");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_twoPlusTwo();
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<int >(__result);
    }

}

#endif // __RcppMP_RcppExports_h__
