// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __RcppMP_h__
#define __RcppMP_h__

#include "RcppMP_RcppExports.h"

#endif // __RcppMP_h__
