// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_RcppMP_RCPPEXPORTS_H_GEN_
#define RCPP_RcppMP_RCPPEXPORTS_H_GEN_

#include "RcppMP_types.hpp"
#include <Rcpp.h>

namespace RcppMP {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("RcppMP", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("RcppMP", "_RcppMP_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in RcppMP");
            }
        }
    }

    inline Rcpp::List rcppmpVersions() {
        typedef SEXP(*Ptr_rcppmpVersions)();
        static Ptr_rcppmpVersions p_rcppmpVersions = NULL;
        if (p_rcppmpVersions == NULL) {
            validateSignature("Rcpp::List(*rcppmpVersions)()");
            p_rcppmpVersions = (Ptr_rcppmpVersions)R_GetCCallable("RcppMP", "_RcppMP_rcppmpVersions");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rcppmpVersions();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

}

#endif // RCPP_RcppMP_RCPPEXPORTS_H_GEN_
