# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Library versions.
#'
#' @description Available multi-precision library versions.
#' @return List of named character vectors indicating the current
#'   versions.
#'
#' @export
rcppmpVersions <- function() {
    .Call('_RcppMP_rcppmpVersions', PACKAGE = 'RcppMP')
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RcppMP_RcppExport_registerCCallable', PACKAGE = 'RcppMP')
})
