# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
twoPlusTwo <- function() {
    .Call('RcppMP_twoPlusTwo', PACKAGE = 'RcppMP')
}

#' @export
test_cpp <- function(args = "") {
    .Call('RcppMP_test_cpp', PACKAGE = 'RcppMP', args)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RcppMP_RcppExport_registerCCallable', PACKAGE = 'RcppMP')
})
