# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Library versions.
#'
#' @description Available multi-precision library versions.
#' @return List of named character vectors indicating the current
#'   versions.
#'
#' @export
rcppmpVersions <- function() {
    .Call('RcppMP_rcppmpVersions', PACKAGE = 'RcppMP')
}

#' Console access to c++ tests.
#'
#' @param args Single or multiple character strings.
#' @export
test_cpp <- function(args = "") {
    .Call('RcppMP_test_cpp', PACKAGE = 'RcppMP', args)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RcppMP_RcppExport_registerCCallable', PACKAGE = 'RcppMP')
})
